apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    service: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      service: shipping
  template:
    metadata:
      labels:
        service: shipping
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      containers:
      - name: shipping
        image: {{ .Values.shipping.image.repo }}:{{ .Values.shipping.image.version }}
        imagePullPolicy: {{ .Values.shipping.image.pullPolicy }}
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 500Mi
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 5
        #   failureThreshold: 30
        #   successThreshold: 1
        # env:
        #   - name: DB_HOSTNAME
        #     value: "mysql"            
        #   - name: DB_PORT
        #     value: "3306"            
        #   - name: DB_NAME
        #     value: "robotstan"            
        #   - name: DB_USERNAME
        #     value: "dbadmin"        # RDS DB Username is dbadmin     
        #   - name: DB_PASSWORD
        #     valueFrom:
        #       secretKeyRef:
        #         name: mysql-db-password
        #         key: db-password   
      restartPolicy: Always
      {{- with .Values.shipping.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.shipping.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.shipping.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
