apiVersion: v1
kind: Service
metadata:
  labels:
    service: mysql
  name: mysql
spec:
  type: ExternalName
  externalName: {{ .Values.mysql.rdsEndpoint }}
  ports:
    - port: 3306
      targetPort: 3306