# Registry and repository for Docker images
# Default is docker/robotshop/image:latest
# image:
#   repo: 415916042243.dkr.ecr.ap-south-1.amazonaws.com/roboshop-user
#   version: 2
#   pullPolicy: IfNotPresent

# EUM configuration
# Provide your key and set the endpoint
eum:
  key: null
  url: https://eum-ap-south-1.instana.io
  #url: https://eum-us-west-2.instana.io

# Pod Security Policy
psp:
  enabled: false

# For the mini ones minikube, minishift set to true
nodeport: false

# "special" Openshift. Set to true when deploying to any openshift flavour
openshift: false

ocCreateRoute: false

######################################
# Affinities for individual workloads
# set in the following way:
# <workload>:
#   affinity: {}
#   nodeSelector: {}
#   tolerations: []
######################################
cart:
  image:
    repo: 415916042243.dkr.ecr.ap-south-1.amazonaws.com/roboshop-user
    version: 2
    pullPolicy: IfNotPresent
  affinity: {}
  nodeSelector: {}
  tolerations: []

